### ISSUE TITLE
Use the ZF1 CLA API

### ISSUE THREAD

**Issue by weierophinney** [gianarb/zfcla-ci#5]
Hi, @gianarb !

We already have an API that our maintainers use for determining if a user has signed a CLA. It allows lookup by either github username or email, and returns either a 404 or a 200 based on the results of the lookup:

- `GET http://framework.zend.com/api/cla/by-email?email=<email>`
- `GET http://framework.zend.com/api/cla/by-username?username=<username>`

Would you be willing to re-work the project to perform the lookup via the API instead? Ideally, we'd look by username first, and, if not found, then by the email address associated with the user via the GitHub API.

Additionally... our servers run PHP. :) If you'd be willing to rewrite to use PHP, with the changes above, I'd definitely put it into effect to simplify the work for our maintainers.

**Comment by gianarb** [comment]
eheh yes I already use api in this project :) No problem I work for a PHP porting

**Comment by gianarb** [comment]
WIP [gianarb/zfcla-ci-php](https://github.com/gianarb/zfcla-ci-php) :+1:
